version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "python manage.py collectstatic --noinput &&
        gunicorn acms.wsgi:application -w 2 -b 0.0.0.0:8000 --reload"
    env_file:
      - .env
    environment:
      LAUNCH_TYPE: webserver
volumes:
  static_volume:
